-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglz2bhPZrGtNkS1+N
vJbm2GakNegpZuSQ4XfNRAFckaKgCgYIKoZIzj0DAQehRANCAAQr6KoojYBFU5Hm
3mU0o9fMNsnZfkVjboWTsqnknANPK3sOpJN3cHMXEdb6hLI2WJfDS1OZMo2XP/Ko
JgHwwc54
-----END PRIVATE KEY-----