name: FarmManagementGame
options:
  bundleIdPrefix: com.farmmanagement
targets:
  FarmManagementGame:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: 
      - Sources
    settings:
      base:
        DEVELOPMENT_TEAM: YOUR_TEAM_ID
        PRODUCT_BUNDLE_IDENTIFIER: com.farmmanagement.game
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    dependencies:
      - framework: WebKit.framework
    scheme:
      testTargets:
        - FarmManagementGameTests
  
  FarmManagementGameTests:
    type: bundle.unit-test
    platform: iOS
    sources: 
      - Tests
    dependencies:
      - target: FarmManagementGame 